spring:
  application:
    name: graphql
    version: 1.0.0

  datasource:
    url: jdbc:postgresql://localhost:5432/graphql
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  graphql:
    graphiql:
      enabled: true
    schema:
      locations: classpath:/graphql/

server:
  port: 8081

logging:
  level:
    org.springframework.graphql: DEBUG
    org.hibernate.SQL: DEBUG
