spring:
  application:
    name: ECommerceBackend_Java_GraphQL
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom-graphQL
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  graphql:
    graphiql:
      enabled: true
    schema:
      locations: classpath:/graphql/

server:
  port: 8080



logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
